  buying  maint doors persons lug_boots safety  class
0  vhigh  vhigh     2       2     small    low  unacc
1  vhigh  vhigh     2       2     small    med  unacc
2  vhigh  vhigh     2       2     small   high  unacc
3  vhigh  vhigh     2       2       med    low  unacc
4  vhigh  vhigh     2       2       med    med  unacc


[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]


[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


[0 1 2 3]


In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [1]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [28]:
car_data =  pd.read_csv('car.data', header = None)

car_data.columns = ['Buying', 'maint', 'doors', 'persons', 'lug_boots', 'safety', 'class']

X=car_data[[
    'Buying',
    'maint',
    'safety'
]].values
y=car_data[['class']]
print(X,y)

Le = LabelEncoder()
for i in range(len(X[0])):
      X[:, i] = Le.fit_transform(X[:,i])
print(X)

# conversion of y
label_mapping ={
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class']=y['class'].map(label_mapping)
y=np.array(y)
print(y)
 # creating the model
knn=neighbors.KNeighborsClassifier(n_neighbors=25,weights='uniform')
X_train, X_test, y_train, y_test =train_test_split(X,y, test_size= 0.2)
knn.fit(X_train,y_train)
prediction= knn.predict(X)
accuracy= metrics.accuracy_score(y, prediction)
print("predictions:", prediction)
print("accuracy:", accuracy)
print("actual:", y[300])
print("predicted value:",knn.predict(X)[300])

[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]       class
0     unacc
1     unacc
2     unacc
3     unacc
4     unacc
...     ...
1723   good
1724  vgood
1725  unacc
1726   good
1727  vgood

[1728 rows x 1 columns]
[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]
[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]
predictions: [0 0 0 ... 0 0 0]
accuracy: 0.7563657407407407
actual: [0]
predicted value: 0


C:\Users\mroha\AppData\Local\Temp\ipykernel_18816\1409505216.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y['class']=y['class'].map(label_mapping)
C:\Users\mroha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:228: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
